### ISSUE TITLE
Move to a different name space

### ISSUE THREAD

**Issue by Stwissel** [unplugged/unplugged-controls#137]
To improve distinction I suggest:

a) move to a different name space and prefix (e.g. unp: )
b) Add a category (and some icons), so the unp controls sit in their own category
c) ulitmately make an extension library for inclusion in all apps

**Comment by whitemx** [comment]
We'll investigate these, my suspicion is that we will be limited what we can do here by what is supported by Teamstudio Unplugged which is the primary deployment target for these controls.

Will update as I find out more.

Matt

**Comment by adnamsale** [comment]
a) and b) should be ok, unless there are some complications with categorization of controls. If so it's probably something we'd want to fix in the engine in any case.

Changing to an extension library is a bigger deal since at that point the controls are no longer in the Domino app so they'd need to become part of the Unplugged engine. As the controls mature that may start to make sense, but at the moment we probably don't want to tie the release cycle of the components to the relatively slow release cycle of engine.

I'm not too familiar with the extension library architecture. If they need to be written in Java (?) then Unplugged will never support native extension libraries and the controls would need to be reimplemented within the engine (much like the standard controls today). That would involve a lot of overhead. I don't know whether it possible to repackage the custom controls we have today in some way as an extension library? If that's the case then it might be possible to support that type of extension library within the engine.

Mark

**Comment by whitemx** [comment]
(a) and (b) are now complete and will be released as part of 1.3
