### ISSUE TITLE
A Control that mimics Mark Leusink's main Contacts view in Continuity

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#150]
(containing avatar thumbnails, with blue separator panels, please also if possible add A - Z selector on right hand side - implemented like the one in Apple's own Contacts app on the iPhone - to allow rapid navigation to a specific letter of the alphabet in longer lists)

**Comment by sives** [comment]
Some Continuity customers will not bother to import thumbnail images.  So, rather than just display a placeholder thumbnail image, the View Control should be able to render the data with just the person names and role names left-justified in the View, with the performance benefits that result from not having images.  This could be automatic, or it could require the setting of a configuration option in the Continuity app.
