### ISSUE TITLE
Recycling elements

### ISSUE THREAD

**Issue by Florenze** [unplugged/unplugged-controls#327]
How does unplugged handle garbage collection?

**Comment by adnamsale** [comment]
Hi,

Sorry for the late response - we don't monitor the controls github for general Unplugged questions. I don't think I understand what's behind the question. Are you seeing a problem with Unplugged that seems to be related to GC?

**Comment by Florenze** [comment]
Yeah i was just wondering is there anything special about GC while using unplugged or is it normal xpages rules? I.E Manuel GC with recycling elements

**Comment by adnamsale** [comment]
Ah, ok. You don't need to recycle in Unplugged. The technical reasons why are different on iOS and Android, but neither platform needs to recycle. We do provide the recycle method on all domino objects so that code written for Domino will run unchanged in Unplugged, but it doesn't do anything and can be omitted in pure Unplugged applications.
