### ISSUE TITLE
Sampler app back navigation on Android

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#338]
When you go into Fonts, tap on a Font category, then try to go back with the Android back button, the app seems to freeze.  You need to tap on the top left Menu button in the header bar to get going again.

**Comment by whitemx** [comment]
My suspicion for this is that you're doing the following...

Opening the sampler to the Dashboard
then going straight to the Font Awesome page 
then clicking back and being shown a blank page

This would equally be the case if you went to any other page from the Dashboard and clicked the Android back button.

This was due to a bug where the Dashboard charts weren't being re-initialised when loaded via Ajax.

This has been fixed in the next build.
