### ISSUE TITLE
Comboing ComboBoxes with partial refresh

### ISSUE THREAD

**Issue by Florenze** [unplugged/unplugged-controls#344]
Im trying to make a new combo box appear after you selected something on a previous combobox but since onChange is not supported and onClick doesn't work on the Individual items. My question is  there a way to do this in unplugged?

**Comment by whitemx** [comment]
With the caveat that this will only work on Unplugged devices, not in web browsers...

My solution would be to write client side Javascript which hides and shows the second combo box and also populates the options in the second combo box if necessary. There's hundreds of examples of this sort of pattern available on the internet, for example: http://stackoverflow.com/questions/8839723/change-values-in-combo-box-by-selection-in-first-combo-box

If you need this to work in web browsers as well as Unplugged then things are a little more difficult because the Domino server does not allow us to submit values to it which were not generated by the server. So for hiding and showing the second combo box I would still use client side JS. But for the second combo box list of options, you will need to generate every possible option and set that as the values, then you can manually remove them and add them as required.

Hope this helps.

Matt
