### ISSUE TITLE
App hangs on rotating

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#377]
Environment:
HTC One Android 4.4.2

Steps to reproduce:
1. Open app and go to dashboard
2. Rotate the screen couple of times

Expected result:
3. No hang on rotating

Actual result:
3. App hands already after second turn. No menus are accessible after that. Also note that it takes around 5 seconds for the screen to rotate.

**Comment by KristelViidik** [comment]
Same on iPhone 5c/7.0.4 and iPad 2/7.0.2

**Comment by whitemx** [comment]
As far as I can tell, the app just is slow to respond. I'm not sure what I can do to counter this. Will investigate in 3.2 timeframe.

**Comment by markokruustuk** [comment]
It actually crashes if you do that two or three times.

**Comment by whitemx** [comment]
This might be one which I need to refer up to the Unplugged dev team, to see if there's anything they can do, all I can do is react to an orientation change, if code is already running I can't interrupt it.

**Comment by adnamsale** [comment]
What exactly are we talking about by 'app' and 'dashboard' so that I can try to reproduce this? There isn't really any code involved in rotation so there's not much I could change in Unplugged but maybe the rotation is triggering something else that's crashing.

**Comment by whitemx** [comment]
Hey there. In the Sampler application which we provide with the Unplugged Controls project, what we're seeing is that inside Unplugged, if you change orientation from the home page of the app multiple times in quick succession then the whole of Unplugged becomes unresponsive for up to a minute. For me, eventually it does catch up, but most users would simply kill the app I suspect.

I think Marko is seeing the Unplugged app crash, but I've not experienced that on an iPad Mini retina or an iPhone 5S.

Like you I'm not sure there's much I can do to capture this. I do re-draw the charts on orientation change but that's not a heavy process, although there is no delay at all on other pages, so I guess that's what the issue is.
