### ISSUE TITLE
Creating picture documents in another database.

### ISSUE THREAD

**Issue by JohnCavil** [unplugged/unplugged-controls#382]
Hey,

We are able to create documents in another place without problem, but when we try to attach a picture to that document it doesn't seem to work. Instead it just creates a document with all the fields EXCEPT the actual picture. We are able to create these pictures from the same database without problem in the same way, so we believe that the problem is that it is creating the pictures in another database.

Is tis something that is not yet possible or do you see any other reason for why this could be happening? Again, everything works fine and the way in which we create these picture documents work perfectly if we just do it from the same database, and we are able to create all other parts of the document, just not the picture.

Thanks.

**Comment by JohnCavil** [comment]
Just an update. Incase you need to see if our code is correct here is the fileupload control we use to save the picture:

<xp:fileUpload id="Body"
                                value="#{document1.Body}" required="true" useUploadname="false"
                                filename="image.jpg" style="width:66%">
                                xp:this.attrs
                                    <xp:attr name="capture"
                                        value="true">
                                    /xp:attr
                                    <xp:attr name="accept"
                                        value="image/*;capture=camera">
                                    /xp:attr
                                /xp:this.attrs
                            /xp:fileUpload

And this is how our formEditor is set up:

<unp:unpFormEditor showbuttons="yes" viewxpagename="unpMain.xsp"
        formname="Memo"  xp:key="facet_1"
        position="menu-aligned" >   unp:this.dbName<![CDATA[#{javascript:var lastslash = database.getFilePath().lastIndexOf("/");
var dbname = "/"+database.getFilePath().substr(0,lastslash)+"/spp_pict.nsf";

return dbname;}]]>/unp:this.dbName

But again it saves the document correctly to the database and so on, but the picture doesn't appear. This is really a big problem for us so it would be great if you had any clue of what was causing it. If you need any additional information or code just write. Or if you have any idea at all as to what could be causing this, we'll try it.

**Comment by RichSharpe** [comment]
Hi John,
This maybe one of two problems:

1) I think (from the above) that the issue is that pictures will not save using our saveDocument technique. The saveDocument triggered from the buttons provided in the UnpEditor will only save text/date based fields.
To create a photo attachment you will either need to do a non-ajax (full page load) from the view that loads the new doc and then use standard XPage controls like xp:buttons etc. OR if you like our layout in the formEditor, have a button/link to take a photo that opens up a new document (full load) that can take the picture and save it to the doc. This video shows how to do it - it uses the 2.x controls but the process is the same for the 3.x controls (I haven't had time to update it): http://www.youtube.com/watch?v=dITMq2eDzcE

2) If you are using Android 4.4 (Kit-Kat) there is an issue with the fileUpload control. Teamstudio are working on a solution to this so if this is the case please let me know and we can take it off-line.

**Comment by JohnCavil** [comment]
Hey,

Thank you so much. It turns out our problem was with saving as you said. Works perfectly now. Just had to make our own save script and it fixed it.
