### ISSUE TITLE
Android rotation issue

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#415]
When you go into a UI element in portrait mode e.g. the Accordion then rotate the screen then you are taken back to the Home screen (or Dashboard screen in the Sampler).

The expected behaviour is to stay in the Accordion but re-render it for landscape mode.

This is happening with many other UI elements. (tested on Samsung Galaxy Tab 3 phablet with a 5.7 inch screen)

**Comment by whitemx** [comment]
I think this may be an Unplugged issue rather than anything to do with the controls. It's certainly not something that I'm doing in the Controls code. Maybe Mark can comment?

**Comment by adnamsale** [comment]
Yup, this is an Unplugged issue. Android likes to restart the current activity when you rotate the device. There's code in Unplugged to prevent this since the browser control is quite capable of adjusting to the new size without needing to reload the page. It turns out that when we updated the minimum Android version from 2.2 to 4.0 in Unplugged 3.1, we needed to change that code. I've made the necessary fix and it'll be in the next Android maintenance release. The Unplugged SPR number is UNP-1436.
